### ISSUE TITLE
The log scrolling feature is broken

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#171]
The log viewer scrolling feature is broken. Steps to reproduce:
```
/data/log$ for i in {1..1000}; do echo "Test $i" >> php-error.log; done
/data/log$ cat php-error.log
Test 1
Test 2
Test 3
Test 4
...
Test 1000
```
However on the logs page, the log viewer only allows to view the entries up to "Test 951", and when scrolling up, the loading wrapper animation flashes but no content is added. Tested with newest master by running `wp-seravo-plugin-update --dev`.

**Comment by ottok** [comment]
This is due to a regression introduced in commit https://github.com/Seravo/seravo-plugin/commit/064428dbe5c0b0d36d87992c04d7bce718a500a6
![image](https://user-images.githubusercontent.com/668724/44679146-ce451f00-aa42-11e8-9f83-22c0bfcc0732.png)

A correct `esc_attr_e` was changed to the non-echoing variang `esc_attr`. The data-* attributes end up empty. Revert that line and it will work again.
