### ISSUE TITLE
Optimize images -page instructions unclear

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#198]
The current UI does not explain enough how it works:
![image](https://user-images.githubusercontent.com/668724/48777165-8993f180-ecda-11e8-8274-01cd3fef4e9d.png)

- Link to docs is missing
- Does not explain that recompressing images is possible even without restricting resolution
- Does not explain that recompression does not happen unless box is ticked
- Does not explain that optimization is done on files on disk and only once per file

**Comment by ottok** [comment]
WIP: https://github.com/Seravo/seravo-plugin/tree/dev-maf

**Comment by mikkoaf** [comment]
![image](https://user-images.githubusercontent.com/16817737/49847910-224df680-fddb-11e8-9ac2-bd39a71b99a6.png)
I have improved the usability of the module with UI-changes in conjunction with the Helpy-articles written.

**Comment by ottok** [comment]
At a first look, this text does not explain why, what and how. It is better than before, but please but a bit more thought into it. Maybe ask others for ideas on what should be said here if you yourself don't have new ideas?

The article https://help.seravo.com/fi/knowledgebase/23-wordpressin-hallinta/docs/119-seravo-plugin-optimoi-kuvia does a slightly better job, but there is still relevant details missing. Try to put yourself in the position of a website owner trying to decide whether or not to tick that box, and is is risky for them or not.

Also we need some kind of feature description page on seravo.com about what image optimization is, that we have it and why users should choose it. And then there are the man pages in the command itself, and seravo.com/docs. Many places that all need to tell the same story, but not have duplicate content..

**Comment by mikkoaf** [comment]
Revised the description text according to given feedback. 
![image](https://user-images.githubusercontent.com/16817737/50088002-6e999c00-020a-11e9-8ac3-97c6560c1dc2.png)
Added less disrupting logic for handling empty input.
Previously empty input fields would return values of 500, which is the agreed minimum for image optimization.
With the current iteration the default value when user begins to use the tool is 4000 and when giving empty input the value is 4000

Helpy article has been also revised so that information relevant to website owners should be better available.

A blog post has has been written which describes the benefits of image optimization.

**Comment by tlxo** [comment]
That much text feels a bit heavy for a UI. I'd limit the text to the amount we currently feature and link to user documentation for details.

**Comment by mikkoaf** [comment]
Closed in #211
