### ISSUE TITLE
Document Seravo postboxes

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#224]
I tried creating a new Seravo postbox but the result looks very ugly. Apparently adding normal <p> tags and content does not result in what I would expect. There was also an awful lot of boilerplate code.

I was thinking maybe I am using it incorrectly? Thus I hope somebody would document in the project README how the Seravo postboxes are supposed to be used so that next time I create a new one the HTML markup, CSS and PHP are correct and end result is something nice out-of-the-box instead of this:
![image](https://user-images.githubusercontent.com/668724/52474707-e7312f00-2ba1-11e9-833c-31fc300e9889.png)

**Comment by mikkoaf** [comment]
Updates-page currently does not use postboxes as for example Tests-page does. Similarily Domains-, Logs-, Mails-, Optimize Images- and Shadows-pages, do not currently support standard postboxes.

**Comment by mikkoaf** [comment]
Documenting the postboxes in Seravo-plugin WIP in https://github.com/Seravo/seravo-plugin/tree/dev/docs

**Comment by l3ku** [comment]
@mikkoaf are you willing to finalize documenting the Postboxes? I think it would also be better that someone else than the feature implementor (me) documents them, because I might be blind to potential design flaws. Thus, at the same time when you are looking at how the Postbox functionality is designed for documenting it, could you also obtain a critical viewpoint for the overall (incl. code-level) design and try to think of improvements?

Could you also add some example code (e.g. adding a new page with postboxes) to the documentation so that it would be easy for developers to follow how to use them?

**Comment by ottok** [comment]
@mikkoaf Is this ready now?

**Comment by mikkoaf** [comment]
@ottok Yes, this is ready.
