### ISSUE TITLE
instance-switcher.js and .css is included for not logged-in users

### ISSUE THREAD

**Issue by thejulle** [Seravo/seravo-plugin#274]
instance-switcher.js is included in the front-end of production sites, even for users that are not logged in to WordPress. Instance switcher uses jQuery, so that is also included along with instance-switcher.js.

Could you change this so instance-switcher.js would only be included for users that are logged in to WordPress? This currently has negative effect to the page speed. Cheers!

**Comment by thejulle** [comment]
Hi, I looked a the commits and believe that this change is has caused the current problem with seravo-plugin 1.9.11:
https://github.com/Seravo/seravo-plugin/commit/a7043034bdfbc7369289c253184d44073f9d0982#diff-1a2d8be517926eee3ec1915e97616b38R66

**Comment by ottok** [comment]
Thanks for debugging this!
Seems the logic was changed intentionally as also the comment changed:
![image](https://user-images.githubusercontent.com/668724/62939390-d3c58180-bdd9-11e9-9182-6668a2e80a25.png)

We need to re-think this. Indeed, it does not make sense to load those assets for millions of users in vain just because a very small minority might need them.

**Comment by JoosuaKoskinen** [comment]
Instance-switcher files should definitely not be loaded for everyone.
