### ISSUE TITLE
Hide instance switcher in local development

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#278]
**Describe the bug**
The instance switcher is shown in development, although the local development environment is not a shadow that can be switched out from.

**To Reproduce**
1. Run `vagrant up`
2. Log into `wordpress.local/wp-admin`
3. The instance switcher is visible while it should not be

**Expected behavior**
The instance switcher should be hidden, or transformed into some other form so that "Poistu varjosta" and "Varjot selitettynä osoitteessa..." should not be accessible.

**Screenshots**
![Screen Shot 2019-08-29 at 15 55 23](https://user-images.githubusercontent.com/24781811/63942020-8e5db100-ca75-11e9-8ad3-3c75e4d07a94.png)
![Screen Shot 2019-08-29 at 15 55 07](https://user-images.githubusercontent.com/24781811/63942008-8a319380-ca75-11e9-91a0-aee5669a2ecb.png)

**Comment by JoosuaKoskinen** [comment]
I don't think this issue is current anymore. Instance switcher had been prevented from loading in Vagrant way before this issue: https://github.com/Seravo/seravo-plugin/commit/6b4f96c2f7ce901fefa17ccffe2c73cd0b52700e.

I think there was a issue with $WP_ENV back then or something but seems to work fine now with `wordpress-beta` Vagrant box.
