### ISSUE TITLE
Add instructions for phpcs

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#346]
**Is your feature request related to a problem? Please describe.**
I'm not aware of any phpcs instructions existing. There's a script for installing it but it still takes some time and failed attempts to get it working as it has dependencies which you have to figure out by yourself. It always takes time to instruct someone how to install phpcs.

**Describe the solution you'd like**
I would like to have the list of dependencies and the basic commands to use it in README.

**Comment by SailaOrvokki** [comment]
I try to install that and I had to ask Joosua helps. So I made these in Finnish. If someone could translate this and read that it is OK?
/home/saila/Asiakirjat/seravo-plugin_Install_phpcs.pdf

**Comment by ottok** [comment]
Why do you want to install phpcs manually? Is there something preventing
you from using the perinstalled one in Seravo Vagrant or Docker?

**Comment by SailaOrvokki** [comment]
I clone seravo-plugin ssh whith my own computer. I doing competence-based qualification to my school like Joosua did. 
I was not able to do that because I do not find nothing instructions, only Install phpcs.

**Comment by ottok** [comment]
PHPCS installation in general is mentioned on https://github.com/squizlabs/PHP_CodeSniffer but you can also just run `apt install phpcs` on Ubuntu.

The script https://github.com/Seravo/seravo-plugin/blob/master/scripts/install-phpcs.sh describes how to install the sniffs that have the WordPress coding standards. The script is intended for CI use but sure, you can also run it manually if you can read the contents and see what the script does and validate if that works for your situation or not.

For Seravo Plugin development in general, the easiest is to run the whole development environment in Vagrant or Docker so that all tooling is pre-installed.

I guess @JoosuaKoskinen could expand https://github.com/Seravo/seravo-plugin#development section in the README to mention on how to use Vagrant or Docker briefly before showing the example of using entr+rsync to develop on a real site.

**Comment by elguitar** [comment]
@JoosuaKoskinen is currently working on this
