### ISSUE TITLE
Speed test panel button is confusing in WP-Admin

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#398]
In WP-admin, clicking the speed test top panel button does nothing. This is confusing.

There's a tooltip, which gives a hint about what is happening, but it can easily go unnoticed.

There are three ways that this can be handled:
1. Remove the button, if the user is in wp-admin
1. Clearly react to the button press and inform the user, that the speed test should be run when not in wp-admin
1. Run the speedtest for home anyway

What do you think @Wiljami ?

**Comment by Moppa5** [comment]
It would most likely be the clearest if the speed-test wasn't available in wp-admin if one can't run it there. I suggested earlier that clicking the button in wp-admin could take the user to the site where the data and statistics are shown and prompt user there.

**Comment by Wiljami** [comment]
I agree the button is confusing as it is now.

I think solution 1. is the simplest and best fix for this issue. It serves as an easy shortcut to speed test the current page.

2. Just gives the user extra things to read instead of actually serving as a tool to improve the functionality.

3. Running speed test at home might be confusing by making them think that it is actually running the test at wp-admin location or that the button is just a shortcut to get to the speed test. The speed test should be rare enough thing to do that navigating to site status to do it is not that big of a deal.

**Comment by Wiljami** [comment]
> It would most likely be the clearest if the speed-test wasn't available in wp-admin if one can't run it there. I suggested earlier that clicking the button in wp-admin could take the user to the site where the data and statistics are shown and prompt user there.

Actually I kinda like this idea, since it would keep the admin bar consistent all over the place without having buttons disappear and appear from it.
