### ISSUE TITLE
WordPress 5.5 breaks postbox top styles

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#438]
**Description**
After updating to WordPress 5.5 I noticed that the top of the Seravo Plugin postbox changes drastically. It seems that some HTML elements of the postbox top are not generated and thus the styles aren't applied. 

The bug has been confirmed on two sites.

**To Reproduce**
1. Take a look at Seravo Plugin postbox on WordPress < 5.5
2. Update WordPress to 5.5
3. Compare step one results with the updated one

**Screenshots**
On WordPress 5.4.x or later the postbox
![Screenshot(1)](https://user-images.githubusercontent.com/16706187/90107609-bd863480-dd51-11ea-9d6b-cb47f379b4dd.png)
Instantly after updating to 5.5 the top is clearly different
![Screenshot(2)](https://user-images.githubusercontent.com/16706187/90108394-e78c2680-dd52-11ea-8c49-50ddc2260980.png)

**Comment by Moppa5** [comment]
After investigating this issue a bit, I think that the position toggle feature on WordPress admin dashboard (added on version 5.5) might be the reason for some styles not being applied. A quick fix with some css tweaks has been done but I'm not sure whether it closes this issue completely. 

![Screenshot](https://user-images.githubusercontent.com/16706187/90131057-27173a80-dd74-11ea-9122-a30ffa69b01a.png)

**Comment by elguitar** [comment]
You are right. The core reason here was that the internal structure Postboxes seems of WordPress due to [Accessibility improvements](https://github.com/WordPress/WordPress/commit/454dab13c1adec275a275ae961ba374fb0bfcfe1#diff-50278328b502f4eb3f2b8b7ab49324a1). @Moppa5 noticed these up-down arrows too.

I managed to create a fix, but it is not compatible with WP 5.4 or earlier versions.

I think that maybe the CSS fix of @Moppa5 is the only way forward. I will investigate :thinking:
