### ISSUE TITLE
"Poistu varjosta" link is not working, if staging has different URL than production

### ISSUE THREAD

**Issue by runomarsista** [Seravo/seravo-plugin#67]
"Poistu varjosta" link is not working, if staging URL different than production. It should be redirected back to production site URL.

Now it's using ?wpp_shadow=clear to make redirection.

**Comment by ottok** [comment]
Staging sites can have their own domains, but it is still in beta and there are known limitations, like this exit link issue and the limited availability of https certificates for arbitrary custom domains on staging sites (eg. https://dev123.example.com/ not working because the certificate for https://example.com/ does not cover it)..

**Comment by nuuttitoivola** [comment]
Closed via https://github.com/Seravo/seravo-plugin/pull/251/commits/bd946bd83becc1369e9e5fe6b22331b585105185
