### ISSUE TITLE
Show site error count to admins, allow easy access to error logs

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#7]
On the fronpage of WP admin there could be a small discreet notification that "you have X lines in your error log this week". That could be a link to a separate section that shows full error log contents, eg. as presented by https://github.com/Seravo/wp-dashboard-log-monitor

**Comment by l3ku** [comment]
Prototype made, also shows the last login to WordPress.

![image](https://cloud.githubusercontent.com/assets/24781811/26782030/2f7d75d8-49fa-11e7-9483-b45960dd9ac2.png)

At the moment, only a maximum of 100 rows is read because increasing this amount might critically affect site performance.

These messages show every time when opening the dashboard page. Is there a method to show these only on login? The repetitive showing of these messages every time the user visits the dashboard page might be annoying...

**Comment by ottok** [comment]
First version implemented in b0b6fbc2e3e711dc0d86ebd9bf229f3654cf529a, but UI and UX need some refining so that we can be sure that admins do see this notification if their site has problems, but that it would not grab unnecessary attention.

**Comment by ottok** [comment]
To finalize this, the login notification should be split into two modules. One that shows _every_ user their last login time and IP/hostname so they can notice if somebody else is using their password. The other part should be a notification about PHP errors to admins (who are the only ones capable of doing something about PHP errors).

**Comment by mikkoaf** [comment]
Currently when non-admins ie. subscribers login, they are redirected to their profile page. This means that these types of users do not see the login notification. https://github.com/Seravo/seravo-plugin/blob/0e1c5c4df72888d26cadefd02d84b31fb87a7df8/modules/login-notification.php#L35
Work in progress in 8acb11a4ab6c. These changes mean that the login notification is shown when ever a user is browses in from the profile-page.

If the correct place to show the login notification is in wp-admin, another method would be to redirect all WordPress users to wp-admin/index.php on login using a filter.

**Comment by Moppa5** [comment]
Not sure what's the current status of this issue. I enhanced this feature by adding a hook for the subscribers case since normally they are redirected to their profile. However, on more complex WordPress sites there could also be own redirections for subscribers too so this doesn't probably handle all cases. On the other hand, on default other than subscribers are redirected to dashboard (index) so I think this would fit in our needs. 

Personally I think the issue could be closed and we can furthermore enhance the last login notification in another thread? 

Comments and ideas?

**Comment by elguitar** [comment]
>To finalize this, the login notification should be split into two modules. One that shows every user their last login time and IP/hostname so they can notice if somebody else is using their password. The other part should be a notification about PHP errors to admins (who are the only ones capable of doing something about PHP errors).

All of this is implemented, except for the notification for subscribers.

Santeri's commit fixes that, so after merging it this can be closed.
