### ISSUE TITLE
Notify customer on wp-admin if version updates has failed

### ISSUE THREAD

**Issue by runomarsista** [Seravo/seravo-plugin#73]

**Comment by simoke** [comment]
So it's propably necessary to extend the plugin to display notifications on WP admin front page (in case that timestamp of the latest successful update is prior than the latest update attempt, or null), or alternatively improve update automation to send email notifications to WP administrative users.

![updates](https://user-images.githubusercontent.com/25475688/31997999-c5799998-b996-11e7-8697-af178583e073.png)

**Comment by elguitar** [comment]
b0b6fbc2e3e711dc0d86ebd9bf229f3654cf529a has some relevant code for showing information in wp-admin's dashboard. For now it shows the last login and the amount of php-errors.

**Comment by l3ku** [comment]
Sending automatic emails regarding failed updates and site errors is currently in progress. I personally don't think it is good practice to flood wp-admin with notifications, so we should really consider if it is necessary to implement this notification in addition to sending emails to customers.

I made a very simple UI into the Seravo Plugin "Updates" page ([WIP](https://github.com/Seravo/seravo-plugin/tree/feature-notification-email-field)) for the customer to enter his/her specified technical contact emails:

![screen shot 2017-12-09 at 16 13 41](https://user-images.githubusercontent.com/24781811/33796425-9392f6b6-dcfc-11e7-8586-b2bd77e61fef.png)

Any opinions on the screenshot above, like is the "Updates" page the correct location for this and is the UI simple enough?

**Comment by ottok** [comment]
In the future, we might have a separate Notifications page, with a fancy add/remove UI fo rmultiple e-mail addresses (or a selection from WP user list to be even fancier), and options for customers to select what notifications they want, and set a limit on how much or how frequently they want to have e-mail, log about recently sent notifications etc.

**But for now, the screenshot above is OK and enough.** Better to have something that works end-to-end with first, and make the fancy things at a later time.

**Comment by annijpesonen** [comment]
The way I understand it, the most important thing would be to send a notification to customers only when there is some permanent issue on their website that makes updating impossible and requires their actions. I don't know if this kind of separation of notifications is possible, because then our system should also be able to automatically detect what the problem is. Or maybe the notification should be sent to us? Like this: "there seems to be a permanent issue on updating this website --> look into it and notify the customer". As far as I know, at the moment we only look for these problems if some customer complains about their site not being updated in a long time.

**Comment by ottok** [comment]
Maybe this should be implemented so, that the notification is shown only on the Reports page in the context of "Site info" and it should say something like "Last successful full site update was over X months ago. A developer should take a look at the update log and fix the issue preventing the site from updating."

Emphasis on
- FULL update
- link to update.log
- never show this on sites that have Seravo updates disabled

**Comment by ottok** [comment]
Challenges:
- link to `/wp-admin/tools.php?page=logs_page&logfile=update.log&max_num_of_rows=50` will not show anything currently if the update.log has rotated
  - If requested log is missing or empty, show the previous log (with dateext but not gzipped). There should be no need to get gzipped files since we have in logrotate `delaycompress` and the previous log should always be uncompressed in cases where the latest log is empty or missing.
  - This could be done in a separate step as it starts to get outside of the scope of this issue.

Design notes:
- Put all updates related into on the updates page. Extending the reports page as described in this issue was a legacy thing since we didn't have the updates page when those comments were added to this issue.

**Comment by mvierma** [comment]
This feature is now implemented in commit 6d6553e
