### ISSUE TITLE
Purge cache -button only purges front proxy cache, should run full wp-flush-cache instead

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#83]
Currently the UI button does not do run wp-purge-cache (alias wp-flush-cache). All of our command line tools should have WP-admin equivalents, so users would expect this button and cli command to do the same thing.

**Comment by ottok** [comment]
I did some tests with this. It does not work with the current code workflow, since the nonce is stored as a transient, and its wiped right in the middle of the request, to the "Success" notice will never show as the nonce will never match...

**Comment by ottok** [comment]
Also, because of the `add_action( 'admin_notices', '_seravo_purge_notification' );'` action, the Purge button only works if wp-admin is open and does nothing when the adminbar is used on the web front.

**Comment by ottok** [comment]
> Flushing the object cache is already done in wp-purge-cache, so running that command would solve the problem.

The architecture needs to be updated first, as currently the command relies on transients, and will not show any response if it cleans out its own transient.

**Comment by l3ku** [comment]
If running `wp-purge-cache`via a link, the Nginx restart that is done causes a "This site can’t be reached" error response code after clicking the "Purge cache" button. Solution: do this with AJAX instead.

**Comment by ottok** [comment]
**The whole architecture** of this command works needs to be changed. It cannot rely on using transients as it would purge it during the run.

**Comment by l3ku** [comment]
How is there a need to verify any nonces anymore after the command has been run? As a first impression, I can not figure out any problems with the workflow that involves:
- Create nonce when loading page
- Send nonce with AJAX request asking for server to purge cache
- Check that the request is valid via nonce ***before*** flushing the cache
- No need to check nonces anymore after the command has been run and the transient is gone

However, I have not tested whether the AJAX request would immediately fail due to a Nginx restart.
